Info:
  Era: 2017
  Channel: MUMU

Z:
  MassCut: 40

Muon:
  LeadingMuonPt: 29
  SubLeadingMuonPt: 15
  Eta: 2.4
  ISO: 0.15
  doMCSmearing: false
  MCSmearing:
    barrel:
      smearing: -1
      sigma: 0.0104 +6.11e-5 * x -3.31e-8 * x^2 + 6.73e-12 * x^3
    endcap:
      smearing: 0.3202
      sigma: 0.0121 + 5.92e-5 * x -2.61e-8 * x^2 + 5.11e-12 * x^3

Jet:
  Pt: 30
  Eta: 2.5
  ID: 6
  PUID: 4
  BTag: M
  Cleaning: false

Correction:
  # Reco: false  # Reserved for the high-pT workflow
  RoccoR: false
  ID: false
  ISO: false
  Trigger: false
  PileUp: false
  L1PreFiring: false
  JetPU: false
  BTag: false
  TopPtReweighing: false

Efficiency:
  # Reco:
  #   Path: ../../correctionlib/muon/high/ScaleFactors_Muon_highPt_RECO_2017_schemaV2.json
  #   Name: NUM_GlobalMuons_DEN_TrackerMuonProbes
  ID:
    Path: ../../correctionlib/muon/tight/ScaleFactors_Muon_IDISO_2017.json
    Name: NUM_TightID_DEN_TrackerMuons_abseta_pt
  ISO:
    Path: ../../correctionlib/muon/tight/ScaleFactors_Muon_IDISO_2017.json
    Name: NUM_TightRelIso_DEN_TightIDandIPCut_abseta_pt
  Trigger:
    Path: ../../correctionlib/muon/tight/ScaleFactors_Muon_Trigger_2017.json
    Data: NUM_IsoMu27_DEN_CutBasedIdTight_and_PFIsoTight_abseta_pt_efficiencyData
    MC: NUM_IsoMu27_DEN_CutBasedIdTight_and_PFIsoTight_abseta_pt_efficiencyMC
  JetPU:
    Path: ../../correctionlib/JetPUID/2017.json
  BTag:
    Path: ../../correctionlib/bTag/2017.json
  BTagEff:
    Path: ../../correctionlib/bTag/eff/BTagEff_MUMU_eff_AbsEta_PtMerged.json

RoccoR:
  Path: ../../RoccoR/RoccoR2017UL.txt

Pileup:
  Data: PileupHistogram-goldenJSON-13tev-2017-69200ub-99bins.root
  MC: MC_2017.root
